title: Peter McNeil
description: Home of Peter McNeil. Part time at BBC News and a final year university student studying Software Engineering.
email: webmaster@pop.ski
url: "https://pop.ski"
lang: en_GB
author: Peter McNeil

source: ./website
destination: ./_site

seo:
  name: Peter McNeil
  type: Person

sass:
  style: compressed
  sass_dir: ./_scss/

jekyll-minifier:
  uglifier_args:
    harmony: true

plugins:
  - jekyll-minifier
  - jekyll-sitemap
  - jekyll-seo-tag

social:
  name: Peter McNeil
  links:
    - https://www.github.com/petermcneil
    - https://www.linkedin.com/in/peter-mcneil/

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

