title: Peter McNeil
description: Home of Peter McNeil. A part time Software Engineer at BBC News and final year university student at the University of Brighton.
email: webmaster@pop.ski
url: "https://pop.ski"
lang: en_GB
author: Peter McNeil

source: ./website
destination: ./_site

plugins:
  - jekyll-minifier
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-webp

seo:
  name: Peter McNeil
  type: Person

sass:
  sass_dir: ./_scss/

jekyll-minifier:
  uglifier_args:
    harmony: true

social:
  name: Peter McNeil
  links:
    - https://www.github.com/petermcneil
    - https://www.linkedin.com/in/peter-mcneil/

webp:
  enabled: true
  quality: 90
  img_dir: ["/assets/images/"]
  formats: [".jpeg", ".jpg", ".png", ".tiff"]

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

